plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\BHAMA\\ai\\bais\\backend"
publishOrigin = "default"
base = "C:\\BHAMA\\ai\\bais\\backend"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]